test:
	g++  -o  demo main.cpp -I/usr/local/include/google -lprofiler -L/usr/local/lib -L/home/longzhiri/running/3rd/lua/lua-5.1.3_coco-1.1.4/src -lluajit -ldl -lpthread 

debug: CPPFLAGS = -g 
debug: test
